[package]
name = "recursive_scraper"
version = "0.1.0"
edition = "2021"


[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
clone_on_ref_ptr = "warn"

[lints]
workspace = true

[dependencies]
reqwest = "0.12"
scraper = "0.19"
tokio = { version = "1", features = ["full", "macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
derive_more = { version = "0.99", features = ["from"] }
surrealdb = "1.5"
anyhow = "1"
futures = "0.3"
lazy_static = "1.5"
lazy-regex = "3.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
async-trait = "0.1"
rand = "0.8"
